server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          default-label: multipleinstances
          uri: https://github.com/renzinhohn/biochip-microservices
          search-paths: /services/configuration-services/biochip-config-data
  application:
    name: config-service
